Vagrant.configure("2") do |config|
    # --- Box base ---
    config.vm.box = "ubuntu_server_25_10"

    # --- Red ---
    config.vm.network "private_network", ip: "192.168.56.2"
    config.vm.network "forwarded_port", guest: 80, host: 8080

    # --- Carpeta compartida ---
    config.vm.synced_folder "./fastapi", "/home/vagrant"
    
    # --- Hardware ---
    config.vm.provider "virtualbox" do |vb|
        vb.name = "ubuntu_server_vagrant_01"
        vb.memory = "2048"
        vb.cpus = 2
    end
    
    # --- Provisión ---
    config.vm.provision "shell", run: "once" do |s|
        s.inline = <<-SHELL
            apt-get update -y
            apt-get install -y python3 python3-pip

            # Crear el entorno virtual fuera del directorio compartido
            python3 -m venv /opt/venv
            /opt/venv/bin/pip install --upgrade pip
            /opt/venv/bin/pip install fastapi uvicorn
        SHELL
    end
end