Vagrant.configure("2") do |config|
    # --- Box base ---
    config.vm.box = "alvistack/ubuntu-24.04"

    # --- Red ---
    config.vm.network "private_network", ip: "192.168.56.2"
    config.vm.network "forwarded_port", guest: 80, host: 8080

    # --- Carpeta compartida ---
    config.vm.synced_folder "./fastapi", "/home/vagrant"
    
    # --- Hardware ---
    config.vm.provider "virtualbox" do |vb|
        vb.memory = "2048"
        vb.cpus = 2
    end
    
    # --- Provisión ---
    config.vm.provision "shell", run: "once" do |s|
        s.inline = <<-SHELL
            apt-get update -y
            #apt-get upgrade -y
            apt-get install -y python3 python3-pip

            # Crear el entorno virtual fuera del directorio compartido
            python3 -m venv /opt/venv
            /opt/venv/bin/pip install --upgrade pip
            /opt/venv/bin/pip install fastapi uvicorn
            
            # Configurar el servidor SSH para aceptar conexiones externas
            #apt-get install -y openssh-server
            #systemctl enable ssh
            #sed -i 's/#Port 22/Port 22/' /etc/ssh/sshd_config
            #sed -i 's/^#*PasswordAuthentication.*/PasswordAuthentication yes/' /etc/ssh/sshd_config
            #systemctl restart sshd
        SHELL
    end
end